"""Docker Bake file generation for dbw."""

from pathlib import Path
from typing import Optional

from jinja2 import Template

from .config import get_buildx_cache_dir, get_env
from .errors import BakeFileError
from .log import get_logger

logger = get_logger(__name__)

# Bake file template
BAKE_HCL_TEMPLATE = """# Generated by dbw - Docker Buildx/Bake Worktree
# Do not edit manually

variable "PLATFORM" {
  default = "{{ platform }}"
}

variable "CACHE_DIR" {
  default = "{{ cache_dir }}"
}

variable "REGISTRY" {
  default = "{{ registry }}"
}

# Base development image
target "base" {
  context = "{{ worktree_path }}"
  dockerfile = "{{ worktree_path }}/Dockerfile"
  tags = ["{{ base_image_tag }}"]
  platforms = [var.PLATFORM]
  
  {% if cache_type == "local" -%}
  cache-from = ["type=local,src=${var.CACHE_DIR}"]
  cache-to = ["type=local,dest=${var.CACHE_DIR},mode=max"]
  {% elif cache_type == "registry" -%}
  cache-from = ["type=registry,ref=${var.REGISTRY}/dbw_base_cache"]
  cache-to = ["type=registry,ref=${var.REGISTRY}/dbw_base_cache,mode=max"]
  {% endif -%}
  
  args = {
    BUILDKIT_INLINE_CACHE = "1"
  }
}

{% for ext in extensions %}
# Extension: {{ ext.name }}
target "ext_{{ ext.name }}" {
  context = "{{ ext.path }}"
  dockerfile = "{{ ext.path }}/Dockerfile"
  tags = ["{{ ext.image_tag }}"]
  platforms = [var.PLATFORM]
  
  {% if cache_type == "local" -%}
  cache-from = ["type=local,src=${var.CACHE_DIR}"]
  cache-to = ["type=local,dest=${var.CACHE_DIR},mode=max"]
  {% elif cache_type == "registry" -%}
  cache-from = ["type=registry,ref=${var.REGISTRY}/dbw_ext_{{ ext.name }}_cache"]
  cache-to = ["type=registry,ref=${var.REGISTRY}/dbw_ext_{{ ext.name }}_cache,mode=max"]
  {% endif -%}
  
  args = {
    BUILDKIT_INLINE_CACHE = "1"
  }
}
{% endfor %}

# Combined group for parallel building
group "default" {
  targets = [
    "base"{% for ext in extensions %},
    "ext_{{ ext.name }}"{% endfor %}
  ]
}

# Extensions only group
group "extensions" {
  targets = [{% for ext in extensions %}
    "ext_{{ ext.name }}"{% if not loop.last %},{% endif %}{% endfor %}
  ]
}
"""


class BakeFileGenerator:
    """Generates Docker Bake files for parallel builds."""

    def __init__(self, worktree_path: Path, project_name: str) -> None:
        self.worktree_path = worktree_path
        self.project_name = project_name
        self.bake_file = worktree_path / "docker-bake.hcl"

    def generate(
        self,
        extensions: list[dict[str, str]],
        platform: str = "linux/amd64",
        cache_type: str = "local",
        registry: Optional[str] = None,
    ) -> Path:
        """Generate Bake file for the current setup.

        Args:
            extensions: List of dicts with 'name', 'path', 'image_tag'
            platform: Target platform
            cache_type: Cache backend type (local, registry, inline)
            registry: Registry URL for registry cache
        """
        logger.info("bake.generate", file=str(self.bake_file), extensions=len(extensions))

        template = Template(BAKE_HCL_TEMPLATE)

        # Prepare template variables
        cache_dir = get_buildx_cache_dir()
        base_image_tag = f"dbw_base_{self.project_name}:latest"

        # Use registry from env if not provided
        if not registry:
            registry = get_env("DBW_CACHE_REGISTRY") or ""

        # Render template
        try:
            content = template.render(
                worktree_path=self.worktree_path,
                platform=platform,
                cache_dir=cache_dir,
                cache_type=cache_type,
                registry=registry,
                base_image_tag=base_image_tag,
                extensions=extensions,
            )

            # Write file
            self.bake_file.write_text(content)
            logger.info("bake.generated", file=str(self.bake_file))

            return self.bake_file

        except Exception as e:
            raise BakeFileError(f"Failed to generate bake file: {e}") from e

    def validate(self) -> bool:
        """Validate generated bake file syntax."""
        if not self.bake_file.exists():
            return False

        try:
            import subprocess

            result = subprocess.run(
                ["docker", "buildx", "bake", "--print", "-f", str(self.bake_file)],
                capture_output=True,
                text=True,
                check=False,
            )

            if result.returncode != 0:
                logger.error("bake.validation_failed", error=result.stderr)
                return False

            logger.debug("bake.validated", file=str(self.bake_file))
            return True

        except Exception as e:
            logger.error("bake.validation_error", error=str(e))
            return False

    def build(
        self,
        targets: Optional[list[str]] = None,
        load: bool = True,
        push: bool = False,
    ) -> None:
        """Execute Bake build.

        Args:
            targets: Specific targets to build (default: all)
            load: Load images to local Docker
            push: Push images to registry
        """
        if not self.bake_file.exists():
            raise BakeFileError("Bake file not found. Run generate() first.")

        cmd = ["docker", "buildx", "bake", "-f", str(self.bake_file)]

        if targets:
            cmd.extend(targets)

        if load:
            cmd.append("--load")

        if push:
            cmd.append("--push")

        logger.info("bake.build", command=" ".join(cmd))

        try:
            import subprocess

            subprocess.run(cmd, check=True, cwd=self.worktree_path)
            logger.info("bake.build_success")

        except subprocess.CalledProcessError as e:
            raise BakeFileError(f"Bake build failed: {e}") from e
        except FileNotFoundError as exc:
            raise BakeFileError("Docker buildx not found. Please install Docker Buildx.") from exc


def setup_buildx_builder(builder_name: str = "dbw_builder") -> None:
    """Ensure Buildx builder exists and is active."""
    import subprocess

    try:
        # Check if builder exists
        result = subprocess.run(
            ["docker", "buildx", "inspect", builder_name],
            capture_output=True,
            check=False,
        )

        if result.returncode != 0:
            # Create builder
            logger.info("buildx.create_builder", name=builder_name)
            subprocess.run(
                ["docker", "buildx", "create", "--name", builder_name, "--use"],
                check=True,
            )
        else:
            # Use existing builder
            subprocess.run(
                ["docker", "buildx", "use", builder_name],
                check=True,
            )

        logger.info("buildx.builder_ready", name=builder_name)

    except subprocess.CalledProcessError as e:
        raise BakeFileError(f"Failed to setup Buildx builder: {e}") from e
    except FileNotFoundError as exc:
        raise BakeFileError("Docker buildx not found. Please install Docker Buildx.") from exc


def cleanup_bake_file(worktree_path: Path) -> None:
    """Clean up generated bake file."""
    bake_file = worktree_path / "docker-bake.hcl"
    if bake_file.exists():
        bake_file.unlink()
        logger.debug("bake.cleaned", file=str(bake_file))
