"""Docker Compose file generation for dbw."""

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ruamel.yaml import YAML

from .config import RepoConfig
from .errors import ComposeConflict, ComposeError
from .extension import ExtensionCache
from .log import get_logger

logger = get_logger(__name__)


@dataclass
class ComposeConfig:
    """Configuration for compose file generation."""

    worktree_path: Path
    project_name: str
    extensions: list[str]
    config: RepoConfig
    base_image: str
    working_dir: Path
    enable_gpu: bool = True
    enable_x11: bool = True


@dataclass
class ServiceConfig:
    """Configuration for service creation."""

    project_name: str
    working_dir: Path
    config: RepoConfig
    enable_gpu: bool = True
    enable_x11: bool = True


yaml = YAML()
yaml.preserve_quotes = True
yaml.width = 4096


def create_base_dockerfile(worktree_path: Path, base_image: str) -> Path:
    """Create base Dockerfile if it doesn't exist."""
    dockerfile_path = worktree_path / "Dockerfile"

    if not dockerfile_path.exists():
        logger.info("dockerfile.create", path=str(dockerfile_path))

        dockerfile_content = f"""# Generated by dbw
FROM {base_image}

# Create dev user matching host user
ARG USER_ID=1000
ARG GROUP_ID=1000
ARG USERNAME=dev

RUN groupadd -g ${{GROUP_ID}} ${{USERNAME}} && \\
    useradd -u ${{USER_ID}} -g ${{GROUP_ID}} -m -s /bin/bash ${{USERNAME}} && \\
    echo "${{USERNAME}} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Install base development tools
RUN apt-get update && apt-get install -y \\
    git \\
    git-lfs \\
    curl \\
    wget \\
    vim \\
    nano \\
    build-essential \\
    python3 \\
    python3-pip \\
    && rm -rf /var/lib/apt/lists/*

# Set up workspace
WORKDIR /workspace
USER ${{USERNAME}}

# Default command
CMD ["/bin/bash"]
"""
        dockerfile_path.write_text(dockerfile_content)
        logger.info("dockerfile.created", path=str(dockerfile_path))

    return dockerfile_path


def generate_compose_file(compose_config: ComposeConfig) -> Path:
    """Generate docker-compose.yml file."""
    logger.info(
        "compose.generate",
        project=compose_config.project_name,
        extensions=compose_config.extensions,
    )

    compose_path = compose_config.worktree_path / "docker-compose.yml"

    # Base compose structure
    compose_data = {
        "version": "3.8",
        "services": {
            "dev": _create_base_service(
                ServiceConfig(
                    project_name=compose_config.project_name,
                    working_dir=compose_config.working_dir,
                    config=compose_config.config,
                    enable_gpu=compose_config.enable_gpu,
                    enable_x11=compose_config.enable_x11,
                )
            )
        },
    }

    # Merge extension fragments
    if compose_config.extensions:
        _merge_extension_fragments(
            compose_data, compose_config.extensions, compose_config.worktree_path
        )

    # Write compose file
    with open(compose_path, "w", encoding="utf-8") as f:
        yaml.dump(compose_data, f)

    # Validate generated compose file
    _validate_compose_file(compose_path)

    logger.info("compose.generated", file=str(compose_path))
    return compose_path


def _create_base_service(service_config: ServiceConfig) -> dict[str, Any]:
    """Create base development service definition."""

    # Get host user info
    user_id = os.getuid()
    group_id = os.getgid()
    username = os.environ.get("USER", "dev")

    service = {
        "build": {
            "context": ".",
            "dockerfile": "Dockerfile",
            "args": {
                "USER_ID": str(user_id),
                "GROUP_ID": str(group_id),
                "USERNAME": username,
            },
        },
        "container_name": f"{service_config.project_name}_dev",
        "hostname": service_config.project_name.replace("_", "-"),
        "working_dir": f"/workspace/{service_config.working_dir.name}",
        "volumes": [
            ".:/workspace",  # Mount current directory
            "/var/run/docker.sock:/var/run/docker.sock",  # Docker-outside-Docker
        ],
        "environment": {
            "TERM": "xterm-256color",
            "COLORTERM": "truecolor",
        },
        "stdin_open": True,
        "tty": True,
        "networks": ["default"],
    }

    # Add SSH agent and keys
    ssh_auth_sock = os.environ.get("SSH_AUTH_SOCK")
    if ssh_auth_sock:
        service["volumes"].append(f"{ssh_auth_sock}:/ssh-agent")
        service["environment"]["SSH_AUTH_SOCK"] = "/ssh-agent"

    # Add SSH keys
    ssh_dir = Path.home() / ".ssh"
    if ssh_dir.exists():
        service["volumes"].append(f"{ssh_dir}:/home/{username}/.ssh:ro")

    # Add X11 forwarding
    if service_config.enable_x11:
        display = os.environ.get("DISPLAY")
        if display:
            service["environment"]["DISPLAY"] = display
            service["volumes"].append("/tmp/.X11-unix:/tmp/.X11-unix:rw")

            # Add xauth if available
            xauth = Path.home() / ".Xauthority"
            if xauth.exists():
                service["volumes"].append(f"{xauth}:/home/{username}/.Xauthority:ro")

    # Add GPU support
    if service_config.enable_gpu:
        # Check if NVIDIA runtime is available
        try:
            import subprocess

            result = subprocess.run(
                ["docker", "info", "--format", "{{.Runtimes}}"],
                capture_output=True,
                text=True,
                check=False,
            )
            if "nvidia" in result.stdout:
                service["deploy"] = {
                    "resources": {
                        "reservations": {
                            "devices": [
                                {
                                    "driver": "nvidia",
                                    "count": "all",
                                    "capabilities": ["gpu"],
                                }
                            ]
                        }
                    }
                }
        except Exception:
            logger.warning("gpu.detection_failed", fallback="disabled")

    # Add config-specific settings
    if service_config.config.env:
        service["environment"].update(service_config.config.env)

    if service_config.config.volumes:
        service["volumes"].extend(service_config.config.volumes)

    if service_config.config.ports:
        service["ports"] = service_config.config.ports

    return service


def _merge_extension_fragments(
    compose_data: dict[str, Any],
    extensions: list[str],
    worktree_path: Path,  # pylint: disable=unused-argument
) -> None:
    """Merge extension fragments into compose data."""
    cache = ExtensionCache()

    for ext_name in extensions:
        if not cache.extension_exists(ext_name):
            logger.warning("extension.missing", name=ext_name, action="skipping")
            continue

        try:
            ext_path = cache.get_extension_path(ext_name)
            fragment_path = ext_path / "docker-compose.fragment.yml"

            # Load extension fragment
            fragment_data = _load_extension_fragment(fragment_path)

            # Merge services
            _merge_extension_services(compose_data, fragment_data)

            # Merge other sections
            _merge_extension_sections(compose_data, fragment_data)

            logger.debug("extension.merged", name=ext_name)

        except ValueError:
            logger.warning("extension.invalid_fragment", name=ext_name, action="skipping")
        except Exception as e:
            logger.error("extension.merge_failed", name=ext_name, error=str(e))
            raise ComposeError(f"Failed to merge extension {ext_name}: {e}") from e


def _merge_extension_services(compose_data: dict[str, Any], fragment_data: dict[str, Any]) -> None:
    """Merge extension services into compose data."""
    if "services" not in fragment_data:
        return

    for service_name, service_def in fragment_data["services"].items():
        if service_name == "dev":
            # Merge into main dev service
            _deep_merge_service(compose_data["services"]["dev"], service_def)
        else:
            # Add as separate service
            if service_name in compose_data["services"]:
                raise ComposeConflict(f"Service '{service_name}' defined in multiple extensions")
            compose_data["services"][service_name] = service_def


def _merge_extension_sections(compose_data: dict[str, Any], fragment_data: dict[str, Any]) -> None:
    """Merge other top-level sections from extension."""
    for section in ["networks", "volumes", "secrets", "configs"]:
        if section not in fragment_data:
            continue

        if section not in compose_data:
            compose_data[section] = {}

        for name, definition in fragment_data[section].items():
            if name in compose_data[section]:
                raise ComposeConflict(f"{section.title()} '{name}' defined in multiple extensions")
            compose_data[section][name] = definition


def _load_extension_fragment(fragment_path: Path) -> dict[str, Any]:
    """Load and validate extension fragment."""
    with open(fragment_path, encoding="utf-8") as f:
        fragment_data = yaml.load(f)

    if not isinstance(fragment_data, dict):
        raise ValueError("Invalid fragment format")

    return fragment_data


def _deep_merge_service(base: dict[str, Any], overlay: dict[str, Any]) -> None:
    """Deep merge service definitions."""
    for key, value in overlay.items():
        if key not in base:
            base[key] = value
        elif isinstance(base[key], dict) and isinstance(value, dict):
            _deep_merge_service(base[key], value)
        elif isinstance(base[key], list) and isinstance(value, list):
            # Extend lists
            base[key].extend(value)
        else:
            # Override scalar values
            base[key] = value


def _validate_compose_file(compose_path: Path) -> None:
    """Validate generated compose file."""
    try:
        import subprocess

        result = subprocess.run(
            ["docker", "compose", "-f", str(compose_path), "config"],
            capture_output=True,
            text=True,
            check=False,
        )

        if result.returncode != 0:
            raise ComposeError(f"Invalid compose file: {result.stderr}")

        logger.debug("compose.validated", file=str(compose_path))

    except FileNotFoundError:
        logger.warning("docker_compose.not_found", validation="skipped")


def cleanup_compose_files(worktree_path: Path) -> None:
    """Clean up generated compose files."""
    files_to_clean = [
        "docker-compose.yml",
        "docker-compose.override.yml",
    ]

    for filename in files_to_clean:
        file_path = worktree_path / filename
        if file_path.exists():
            file_path.unlink()
            logger.debug("compose.cleaned", file=str(file_path))
